# ============================================================================
# LOGS REPOSITORY
# ============================================================================
# This file was auto-generated on: 2025-10-17 00:30:33 WAT
# It contains asynchronous functions for managing access to the database
# in a MongoDB database using FastAPI.
#
# DO NOT EDIT THIS FILE MANUALLY - RE-RUN THE GENERATOR INSTEAD. OR IF YOU WANT TO EDIT JUST ADD LEAVE OTHER FUNCTIONS THE WAY YOU MET THEM
# ============================================================================

from pymongo import ReturnDocument
from core.database import db
from fastapi import HTTPException,status
from typing import List,Optional
from schemas.logs import LogsUpdate, LogsCreate, LogsOut

async def create_logs(logs_data: LogsCreate) -> LogsOut:
    logs_dict = logs_data.model_dump()
    result =await db.logss.insert_one(logs_dict)
    result = await db.logss.find_one(filter={"_id":result.inserted_id})
    returnable_result = LogsOut(**result)
    return returnable_result

async def get_logs(filter_dict: dict) -> Optional[LogsOut]:
    try:
        result = await db.logss.find_one(filter_dict)

        if result is None:
            return None

        return LogsOut(**result)

    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"An error occurred while fetching logs: {str(e)}"
        )
    
async def get_logss(filter_dict: dict = {},start=0,stop=100) -> List[LogsOut]:
    try:
        if filter_dict is None:
            filter_dict = {}

        cursor = (db.logss.find(filter_dict)
        .skip(start)
        .limit(stop - start)
        )
        logs_list = []

        async for doc in cursor:
            logs_list.append(LogsOut(**doc))

        return logs_list

    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"An error occurred while fetching logss: {str(e)}"
        )
async def update_logs(filter_dict: dict, logs_data: LogsUpdate) -> LogsOut:
    print(logs_data.model_dump(exclude=None))
    result = await db.logss.find_one_and_update(
        filter_dict,
        {"$set": logs_data.model_dump(exclude_none=True)},
        return_document=ReturnDocument.AFTER
    )
    returnable_result = LogsOut(**result)
    return returnable_result

async def delete_logs(filter_dict: dict):
    return await db.logss.delete_one(filter_dict)